import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "@/componets/mainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full h-screen flex justify-center items-center ${inter.className}`}>
        <div className="max-w-screen-md h-screen flex-grow">
          <MainLayout>{children}</MainLayout>
        </div>
      </body>
    </html>
  );
}
